<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/teacher/teacher_left.css" rel="StyleSheet" type="text/css">
	<script src="/js/jquery-1.12.0.js" type="text/javascript"></script>
	<script src="/js/teacher/teacher_left.js?1" type="text/javascript"></script>
</head>
<body>
	<div id="left">
		<div class="parent_title bg_img" id="parent_info" title="个人资料">个人资料</div>
			<div id="child_info" style="display:block" class="child_title">
				<a href="/Teacherinfo/information" target="right" class="bgcolor" id="info_show" title="个人信息">个人信息</a>
				<a href="/Teacherinfo/info" target="right" class="bgcolor" id="info_alter" title="修改信息">修改信息</a>
			</div>
		<div class="parent_title" id="parent_course" title="添加课程">添加课程</div>
			<div id="child_course" style="display:none" class="child_title">
				<a href="/Createcourse/addcourseui" target="right" class="bgcolor" title="添加课程信息">添加课程信息</a>
				<a href="/Createcourse/altercourseui" target="right" class="bgcolor" title="修改课程">修改课程</a>
			</div>
		<div class="parent_title" id="parent_courseinfo" title="查看选课">查看选课</div>
			<div id="child_courseinfo" style="display:none" class="child_title">
				<a href="/Courseinfo/number" target="right" class="bgcolor" title="课程人数">课程人数</a>
				<a href="/Courseinfo/time" target="right" class="bgcolor" title="分配课程">分配课程</a>
				<a href="/Courseinfo/curriculum" target="right"  class="bgcolor" title="课程时间">课程时间</a>	
			</div>	
		<div class="parent_title" id="parent_mark" title="成绩考核">成绩考核</div>
			<div id="child_mark" style="display:none" class="child_title">
				<a href="/Mark/mark" target="right" class="bgcolor" title="成绩评分">成绩评分</a>
			</div>	
		<div class="parent_title" id="parent_remark" title="我的评价">我的评价</div>
			<div id="child_remark" style="display:none" class="child_title">
				<a href="/Evaluation/evaluation" target="right" class="bgcolor" title="查看评价">查看评价</a>
			</div>
		<div class="parent_title" id="parent_upload" title="上传资料">上传资料</div>
			<div id="child_upload" style="display:none" class="child_title">
				<a href="/Upload/uploadui" target="right" class="bgcolor" title="资料上传">资料上传</a>	
				<a href="/Upload/getfile" target="right" class="bgcolor" title="查看上传资料">查看上传资料</a>	
			</div>	
		<div class="parent_title" id="parent_admin" title="联系管理员">联系管理员</div>
			<div id="child_admin" style="display:none" class="child_title">
				<a href="/Contact/contact" target="right" class="bgcolor" title="邮箱联系">邮件联系</a>
			</div>
	</div>	
</body>
</html>