<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>注册页面</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/register/register.css?1" rel="StyleSheet" type="text/css">
	<script type="text/javascript" src="/js/jquery-1.12.0.js"></script>
	<script type="text/javascript" src="/js/box/zDialog.js"></script>
	<script type="text/javascript" src="/js/register/register.js"></script>	
</head>
<body>
	<div id="index">
		<a href="/Index/index" title="回到首页">首页</a>
	</div>
	<div id="register">
		<fieldset>
			<legend>注册页面</legend>
			<form>
				<div>
					姓　　名：<input type="text" name="name" class="name" id="name" placeholder="请输入姓名"/><span id="name_info"></span>
				</div>
				<div>
					学　　号：<input type="text" name="account" class="account" id="account" placeholder="请输入学号" /><span id="account_info"></span>
				</div>
				<div>
					密　　码：<input type="password" name="password" id="password" class="password" placeholder="请输入密码" /><span id="password_info"></span>
				</div>
				<div>
					确认密码：<input type="password" name="repassword" id="repassword" class="repassword" placeholder="请重复密码"/><span id="repassword_info"></span>
				</div>
				<div id="vcode">
					验证码　：<input type="text" name="code" id="code" class="code" placeholder="请输入验证码" /><span id="code_info"></span>
					<label><img src="/Code/code" onclick="javascript:this.src='/Code/code?tm='+Math.random();" /></label>
				</div>
			</form>
			<div id="btn">
				<button type="button" id="sub" title="提交注册">提交注册</button>
			</div>
		</fieldset>
	</div>
</body>
</html>