<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/admin/add_teacher.css?2" rel="StyleSheet" type="text/css">
	<script type="text/javascript" src="/js/jquery-1.12.0.js"></script>
	<script type="text/javascript" src="/js/admin/add_teacher.js?4"></script>
</head>
<body>
	<div id="addteacher">
		<form>
			<div class="left"><input type="text" name="name" id="name" placeholder="姓名" /></div>
			<div id="name_note" class="right"></div>
			<div class="left"><input type="text" name="account" id="account" placeholder="工号" /></div>
			<div id="account_note" class="right"></div>
			<div class="left"><input type="password" name="password" id="psw" placeholder="密码" /></div>
			<div id="psw_note" class="right"></div>
			<div class="left"><input type="password" name="repassword" id="repsw" placeholder="确认密码" /></div>
			<div id="repsw_note" class="right"></div>
		</form>
		<button type="button" id="add" title="添加教师">添加</button>
	</div>
</body>
</html>