<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/admin/release.css" rel="StyleSheet" type="text/css">
	<script src="/js/jquery-1.12.0.js" type="text/javascript"></script>
	<script src="/js/box/zDialog.js" type="text/javascript"></script>
	<script src="/js/admin/release.js?1" type="text/javascript"></script>
</head>
<body>
	<div id="releaselist">
		<form>
			<div id="title">
				<input type="text" name="releaseTitle" id="releaseTitle" placeholder="请输入通知主题"/>
			</div>
			<div id="release">
				<textarea name="releaseContent" id="releaseContent" placeholder="请输入通知内容"></textarea>
			</div>
		</form>
		<div><button type="button" id="sub" title="发布通知">发布通知</button></div>
	</div>
</body>
</html>