<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/teacher/mark.css?2" rel="stylesheet" type="text/css">
	<script src="/js/jquery-1.12.0.js" type="text/javascript"></script>
	<script src="/js/box/zDialog.js" type="text/javascript"></script>
	<script src="/js/teacher/mark.js" type="text/javascript"></script>
</head>
<body >
	<div id="markinfo">
		<div id="selectCourse">
			<div id="left">选择评分科目:</div>
			<div id="right">
				<select name="coursename" id="select">
					<option>--选择科目--</option>
					<?php if(count($this->courses)){foreach($this->courses as $id=>$course){?>
						<option courseid="<?=$course['course_id'] ?>"><?=$course['course_name']?></option>
					<?php }}else{?>
						<option>暂无</option>
					<?php }?>
				</select>
				<button typt="button" id="search" title="检索">检索</button>
			</div>
		</div>
		<div id="marklist">
			<div id="note">请选择科目</div>
		</div>
	</div>	
</body>
</html>