<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/student/information.css?2" type="text/css" rel='StyleSheet'>
</head>
<body>
	<table>
		<tr>
		<td class="title">学号：</td><td><?=$this->account ?></td><td class="title">姓名：</td><td><?=$this->name ?></td>
		</tr>
		<tr>
		<td class="title">性别：</td><td><?=$this->sex ?></td><td class="title">身份证号：</td><td><?=$this->personID ?></td>
		</tr>
		<tr>
		<td class="title">民族：</td><td><?=$this->nation ?></td><td class="title">出生日期：</td><td><?=$this->brith ?></td>
		</tr>
		<tr>
		<td class="title">籍贯：</td><td><?=$this->address ?></td><td class="title">政治面貌：</td><td><?=$this->member ?></td>
		</tr>
		<tr>
		<td class="title">学院：</td><td><?=$this->mycollege ?></td><td class="title">专业：</td><td><?=$this->professional ?></td>
		</tr>
		<tr>
		<td class="title">班级：</td><td><?=$this->myclass ?></td><td class="title">宿舍：</td><td><?=$this->hostel ?></td>
		</tr>
		<tr>
		<td class="title">入学时间：</td><td><?=$this->date ?></td><td class="title">备注：</td><td><?=$this->note ?></td>
		</tr>
	</table>
</body>
</html>