<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>管理员主页</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<frameset rows="120,*,40" border="0" >
	<frame noresize="noresize" src="/Global/top" scrolling="no" name="top" />		
		<frameset cols="200,*">
			<frame noresize="noresize" src="/Admin/left" name="left"/>	
			<frame src="/Admin/right" noresize="noresize" name="right" />
		</frameset>
	<frame src="/Global/bottom" noresize="noresize" name="bottom" scrolling="no" />
</frameset>
</html>