<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/teacher/course_number.css" type="text/css" rel="StyleSheet">
</head>
<body >
	<div id="coursenumber">
		<table>
			<tr id="tabletitle">
				<td>课程编号</td><td>课程名：</td><td>已选人数</td>
			</tr>	
			<?php if(count($this->courseinfo)){foreach ($this->courseinfo as $key=>$course){?>
			<tr class="lists">
				<td class="tdID"><?=$course['course_id']?></td><td><?=$course['course_name'] ?></td><td><?=$course['course_number'] ?></td>
			</tr>	
			<?php }}else{ ?>
			<tr><td colspan='3' id="note">暂无信息</td></tr>
			<?php }?>	
		</table>
	</div>
</body>
</html>