<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/teacher/course_time.css" type="text/css" rel="StyleSheet">
	<script src="/js/jquery-1.12.0.js" type="text/javascript"></script>
	<script src="/js/box/zDialog.js" type="text/javascript"></script>
	<script src="/js/teacher/course_time.js?2" type="text/javascript"></script>
</head>
<body >
	<div id="timetable">
		<form>
			<table>
				<tr id="tabletitle">
					<td>星期：</td><td>一</td><td>二</td><td>三</td><td>四</td><td>五</td>
				</tr>	
				<tr>
					<td class="daytime">早一：</td><td><input type="text" name="11" /></td><td><input type="text" name="21" /></td>
								   <td><input type="text" name="31" /></td><td><input type="text" name="41" /></td>
								   <td><input type="text" name="51" /></td>
				</tr>
				<tr>
					<td class="daytime">早二：</td><td><input type="text" name="12" /></td><td><input type="text" name="22" /></td>
								   <td><input type="text" name="32" /></td><td><input type="text" name="42" /></td>
								   <td><input type="text" name="52" /></td>
				</tr>
				<tr>
					<td class="daytime">午一：</td><td><input type="text" name="13" /></td><td><input type="text" name="23" /></td>
								   <td><input type="text" name="33" /></td><td><input type="text" name="43" /></td>
								   <td><input type="text" name="53" /></td>
				</tr>
				<tr>
					<td class="daytime">午二：</td><td><input type="text" name="14" /></td><td><input type="text" name="24" /></td>
								   <td><input type="text" name="34" /></td><td><input type="text" name="44" /></td>
								   <td><input type="text" name="54" /></td>
				</tr>
				<tr>
					<td class="daytime">晚一：</td><td><input type="text" name="15" /></td><td><input type="text" name="25" /></td>
								   <td><input type="text" name="35" /></td><td><input type="text" name="45" /></td>
								   <td><input type="text" name="55" /></td>
				</tr>
			</table>
		</form>
			<div id="btn">
				<button type="button" id="sub" title="提交">提交</button>
			</div>
	</div>

</body>
</html>