<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<link href="/css/teacher/curriculum_course.css?2" type="text/css" rel="StyleSheet">
	<script src="/js/jquery-1.12.0.js" type="text/javascript"></script>
	<script src="/js/box/zDialog.js" type="text/javascript"></script>
	<script src="/js/teacher/curriculum_course.js?2" type="text/javascript"></script>
</head>
<body >
	<div id="curriculumlist">
		<table>
			<tr id="tabletitle">
				<td>星期：</td><td>一</td><td>二</td><td>三</td><td>四</td><td>五</td>
			</tr>	
			<?php if(count($this->curriculum)){foreach($this->curriculum as $key=>$val){?>
				<tr class="lists">	
					<td class="tdID">第<?=$key+1 ?>节</td>
					<td class="change" coursename="<?=$val[0]['courseTime_id']?>"><?=$val[0]['courseTime_courseName'] ?></td>
					<td class="change" coursename="<?=$val[1]['courseTime_id']?>"><?=$val[1]['courseTime_courseName'] ?></td>
					<td class="change" coursename="<?=$val[2]['courseTime_id']?>"><?=$val[2]['courseTime_courseName'] ?></td>
					<td class="change" coursename="<?=$val[3]['courseTime_id']?>"><?=$val[3]['courseTime_courseName'] ?></td>
					<td class="change" coursename="<?=$val[4]['courseTime_id']?>"><?=$val[4]['courseTime_courseName'] ?></td>
				</tr>
			<?php }}else{ ?>
				<tr><td colspan='6' id="note">暂无信息</td></tr>
			<?php }?>
		</table>
		<div id="tip">*双击可修改</div>
	</div>
</body>
</html>