<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/student/student_left.css" rel="StyleSheet" type="text/css">
	<script src="/js/jquery-1.12.0.js" type="text/javascript"></script>
	<script src="/js/student/student_left.js" type="text/javascript"></script>
</head>
<body>
	<div id="left">
		<div class="parent_title bg_img" id="parent_info" title="个人资料">个人资料</div>
			<div id="child_info" style="display:block" class="child_title">
				<a href="/Information/information" target="right" class="bgcolor" id="info_show" title="个人信息">个人信息</a>
				<a href="/Information/info" target="right" class="bgcolor" id="info_alter" title="修改信息">修改信息</a>
			</div>
		<div class="parent_title" id="parent_selectcourse" title="网上选课">网上选课</div>
			<div id="child_selectcourse" style="display:none" class="child_title">
				<a href="/Selectcourse/selectcourse" target="right" class="bgcolor" title="选课内容">选课内容</a>
				<a href="/Selectcourse/selectresult" target="right" class="bgcolor" title="选课结果">选课结果</a>
				<a href="/Selectcourse/curriculum" target="right" class="bgcolor" title="查看课表">查看课表</a>
			</div>	
		<div class="parent_title" id="parent_mymark" title="学生成绩">学生成绩</div>
			<div id="child_mymark" style="display:none" class="child_title">
				<a href="/Mymark/mymark" target="right" class="bgcolor" title="查看成绩">查看成绩</a>
			</div>	
		<div class="parent_title" id="parent_evaluation" title="教师评价">教师评价</div>
			<div id="child_evaluation" style="display:none" class="child_title">
				<a href="/evaluate/evaluate" target="right" class="bgcolor" title="教师评价">教师评价</a>
			</div>
		<div class="parent_title" id="parent_other" title="其他">其他</div>
			<div id="child_other" style="display:none" class="child_title">
				<a href="/Other/downloadinfo" target="right" class="bgcolor" title="相关下载">相关下载</a>
				<a href="/Other/modify" target="right" class="bgcolor" title="修改密码">修改密码</a>
			</div>	
	</div>
</body>
</html>