<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/teacher/contact.css?2" rel="StyleSheet" type="text/css">
	<script type="text/javascript" src="/js/jquery-1.12.0.js"></script>
	<script type="text/javascript" src="/js/box/zDialog.js"></script>
	<script type="text/javascript" src="/js/teacher/contact.js?1"></script>
</head>
<body>
	<div id="maillist">
		<form>
			<div id="maintitle">
				邮件主题：<input type="text" name="mailSubject" placeholder="请输入邮件主题" />
			</div>
			<div id="contact">
				邮件内容：<textarea rows="10" cols="50"  name="contents" placeholder="请输入邮件内容" ></textarea>
			</div>
			<div id="btn">
				<button type="button" id="sub" title="发送">发送</button>
			</div>
		</form>
	</div>
</body>
</html>