<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/teacher/add_course.css?1" type="text/css" rel="StyleSheet" >
	<script type="text/javascript" src="/js/jquery-1.12.0.js"></script>
	<script type="text/javascript" src="/js/box/zDialog.js?1"></script>
	<script type="text/javascript" src="/js/teacher/add_course.js?1"></script>	
</head>
<body>
	<div id="add_course">
		<form>
			<table>
				<tr id="tabletitle">
					<td>选择课程表:</td><td id='term'><?=$this->now ?></td>
				</tr>
				<tr id="coursetitle">
					<td>课程名:</td><td>学分:</td>
				</tr>
				<tr>
					<td><input type="text" name="course1" /></td><td><input type="text" name="credit1" /></td>
				</tr>
				<tr>
					<td><input type="text" name="course2" /></td><td><input type="text" name="credit2" /></td>
				</tr>
				<tr>
					<td><input type="text" name="course3" /></td><td><input type="text" name="credit3" /></td>
				</tr>
			</table>	
		</form>
		<div id="btn">
			<button type="button" id="add" title="继续添加">继续添加</button>
			<button type="button" id="sub" title="提交">提交</button>
		</div>
	</div>
</body>
</html>