<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/teacher/alter_course.css" type="text/css" rel="StyleSheet" >
	<script type="text/javascript" src="/js/jquery-1.12.0.js"></script>
	<script type="text/javascript" src="/js/box/zDialog.js"></script>
	<script type="text/javascript" src="/js/teacher/alter_course.js?7"></script>	
</head>
<body>
	<div id="altercourse">
		<table>
			<tr id="tabletitle">
				<td>课程编号</td><td>已安排课程</td><td>学分</td><td>操作</td>
			</tr>
			<?php if(count($this->courses)){ foreach ($this->courses as $key => $course){ ?>
			<tr class="lists">
				<td class="tdID"><?=$course['course_id'] ?></td>
				<td><?=$course['course_name'] ?></td>
				<td><?=$course['course_credit'] ?></td>
				<td><a href="javascript:void(0)" class="deletecourse" title="删除该课程" courseid="<?=$course['course_id'] ?>" >删除</td>
			</tr>
			<?php }}else{?>
			<tr><td id="note" colspan="4">暂无课程</td></tr>
			<?php }?>
		</table>
	<div>
</body>
</html>