<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/student/selectCourse.css" rel="StyleSheet" type="text/css">
	<script src="/js/jquery-1.12.0.js" type="text/javascript"></script>
	<script src="/js/box/zDialog.js" type="text/javascript"></script>
	<script src="/js/student/selectCourse.js" type="text/javascript"></script>
</head>
<body >
	<div id="selectlist">
		<form> 
			<table>
				<tr id="tabletitle">
					<td>id</td><td>课程名</td><td>学分</td><td>选择</td>
				</tr>
				<?php if(count($this->Courses)){foreach ($this->Courses as $val){ ?>
				<tr class="lists">
					<td class='tdID'><?=$val['course_id'] ?></td>
					<td><?=$val['course_name'] ?></td>
					<td><?=$val['course_credit'] ?></td>
					<td><input type="checkbox" name="select[]" value="<?=$val['course_id'] ?>" /></td>
				</tr>
				<?php }}else{?>
					<tr><td colspan='4' id="note">暂无可选课程信息</td></tr>
				<?php }?>
			</table>
		</form>
		<div id="btn">
			<button type="button" id="sub" title="提交选课">提交选课</button>
		</div>	
	</div>
</body>
</html>