<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<link href="/css/student/evaluate.css" rel="StyleSheet" type="text/css">
	<script src="/js/jquery-1.12.0.js" type="text/javascript"></script>
	<script src="/js/box/zDialog.js" type="text/javascript"></script>
	<script src="/js/student/evaluate.js" type="text/javascript"></script>
</head>
<body>
	<div id="evaluatelist">
		<form>
			<table>
				<tr id="tabletitle">
					<td>教师工号</td><td>教师</td><td>评价</td><td>评分</td>
				</tr>
				<?php if(count($this->teachers)){foreach ($this->teachers as $key=>$teacher){?>
					<tr class="lists">
						<td><?=$teacher['teacher_account']?></td>
						<td><?=$teacher['teacher_name'] ?></td>
						<td><textarea name="evalation[<?=$teacher['teacher_account']?>]"></textarea></td>
						<td>
							<label><input type="radio" name="mark[<?=$teacher['teacher_account']?>]" value="5" />5分</label>
							<label><input type="radio" name="mark[<?=$teacher['teacher_account']?>]" value="4" />4分</label>
							<label><input type="radio" name="mark[<?=$teacher['teacher_account']?>]" value="3" />3分</label>
							<label><input type="radio" name="mark[<?=$teacher['teacher_account']?>]" value="2" />2分</label>
							<label><input type="radio" name="<mark[?=$teacher['teacher_account']?>"] value="1" />1分</label>
						</td>
					</tr>
				<?php }}else{?>
					<tr><td id="note" colspan="4">您已全部评价</td></tr>
				<?php }?>
			</table>
		</form>
		<div id="btn">
			<button type="button" id="sub" title="提交评论">提交评论</button>
		</div>
	</div>
</body>
</html>