<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<script src="/js/jquery-1.12.0.js" type="text/javascript"></script>
	<script src="/js/box/zDialog.js" type="text/javascript"></script>
</head>
<body>
	<script tyep="text/javascript">
		setTimeout('window.location.href="<?=$this->address ?>"',2000);
		box('ok',"<?=$this->tip ?>");	
	</script>
</body>
</html>