<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/global/top.css" rel="stylesheet" type="text/css">
</head>
<body>
	<div id="quit"><a href="/Global/quit" title="退出系统">退出</a></div>
	<div id="registrar"><a href="/Global/jumpinfo" id="personinfo" target="right" title="个人信息"><?=$this->registrar?></div>
</body>
</html>