<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<title>正在配置教务管理OA系统</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link href="/css/install/config.css" rel="StyleSheet" type="text/css" >
		<script type="text/javascript" src="/js/jquery-1.12.0.js"></script>
	</head>

	<body>
			<center>
				<p id="title">系统正在配置中.....</p>
				<div id="configRes">
				</div>
				<button type="button" style="display:none;" id="enter" title="进入管理系统">进入我的管理系统</button>
				<button type="button" style="display:none;" id="old" title="上一步">上一步</button>
			</center>
		<script>
				var tips = <?=json_encode($this->tips) ?>;
				var i = 0;
				var id = setInterval(function(){
					$("#configRes").append("<p>"+tips[i]+"</p>");
					i++;
					if(i>=tips.length){
						if(tips[i-1] == "配置成功!"){
							document.getElementById('enter').style.display = "block";
						}else{
							document.getElementById('old').style.display = "block";
						}
						clearInterval(id);
					};
				},1000);
				//进入系统
				$("#enter").click(function(){
					window.location.href="http://sust.com";
				});
				//返回上一步
				$("#old").click(function(){
					window.location.href="http://sust.com/install/install";
				});
		</script>
	</body>

</html>