<!DOCTYPE html>
<html>
	<head>
		<title>准备配置教务管理OA系统</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link href="/css/install/install.css" rel="StyleSheet" type="text/css">
		<script src="/js/jquery-1.12.0.js" type="text/javascript" ></script>
		<script src="/js/install/install.js?20160301" type="text/javascript"></script>
	</head>

	<body>
		<center>
			<form action="/Install/config" method="post" id="form">
				<table>
					<tr>
						<td class="text-left">请输入您准备为该系统创建的数据库名：</td>
						<td class="text-right"><input type="text" name="database" id="database" /><span id="database_note"></span></td>
					</tr>
					<tr><td></td><td class="tip" id="database_info"></td></tr>

					<tr>
						<td class="text-left">请输入您准备为该系统创建的默认管理员名：</td>
						<td class="text-right"><input type="text" name="admin" id="admin"/><span id="admin_note"></span></td>
					</tr>
					<tr><td></td><td class="tip" id="admin_info"></td></tr>

					<tr >
						<td class="text-left">请输入您准备为该系统创建的默认管理员密码：</td>
						<td class="text-right"><input type="password" name="password" id="psw"/><span id="psw_note"></span></td>
					</tr>
					<tr><td></td><td class="tip" id="psw_info"></td></tr>

					<tr>
						<td class="text-left">请确认您为该系统创建的默认管理员密码：</td>
						<td class="text-right"><input type="password" name="repassword" id="repsw"/><span id="repsw_note"></span></td>
					</tr>
					<tr><td></td><td class="tip" id="repsw_info"></td></tr>
				</table>	
			</form>
				<button type="button" title="下一步">下一步</button>
		</center>
	</body>

</html>