<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/teacher/get_file.css?1" type="text/css" rel="StyleSheet">
	<script src="/js/jquery-1.12.0.js" type="text/javascript"></script>
	<script src="/js/box/zDialog.js" type="text/javascript"></script>
	<script src="/js/teacher/get_file.js?2" type="text/javascript"></script>
</head>
<body>
	<div id='filetable'>
		<table>
			<tr id="tabletitle">
				<td>文件名</td><td>上传人</td><td>文件介绍</td><td>上传时间</td><td>操作</td>
			</tr>
			<?php if(count($this->fileinfo)){foreach ($this->fileinfo as $key=>$info) {?>
				<tr class="lists">
					<td><?=$info['files_fileName'] ?></td>
					<td><?=$info['files_authorName'] ?></td>
					<td><?=$info['files_intro'] ?></td>
					<td><?=$info['files_time'] ?></td>
					<td><a href="javascript:void(0)" class="deletefile" fileid="<?=$info['files_id']?>" title="删除">删除</a>
					</td>
				</tr>
			<?php }}else{?>
				<tr><td colspan='5' id="note">暂无上传文件</td></tr>
			<?php }?>
		</table>
	</div>
</body>
</html>