<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/teacher/upload_file.css?1" type="text/css" rel="StyleSheet">
	<script src="/js/jquery-1.12.0.js" type="text/javascript"></script>
	<script src="/js/box/zDialog.js" type="text/javascript"></script>
	<script src="/js/teacher/upload_file.js?2" type="text/javascript"></script>
</head>
<body>
	<div id="filelist">
		<form enctype="multipart/form-data" name="myform" method="POST" action="/Upload/upload">
			<div id="filename">
				文件名：<input type="text" name="mainTitle" id="file_name" placeholder="请输入文件名"/>
			</div>
			<div id="introducation">
				介&nbsp;绍：<textarea name="fileIntroduce" id="file_intro" placeholder="请输入文件介绍"></textarea>
			</div>
			<div id="file">
				文&nbsp;件：<input type="file" id="myfile" name="myfile" />
			</div>
			<div id="note"></div>
		</form>
		<div><button type="button" id="sub" title="上传文件">上传</button></div>
	</div>
</body>
</html>