<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/teacher/teacher_info.css?4" rel="StyleSheet" type="text/css">
	<script src="/js/jquery-1.12.0.js" type="text/javascript"></script>
	<script src="/js/box/zDialog.js" type="text/javascript"></script>
	<script src="/js/teacher/teacher_info.js?3" type="text/javascript"></script>
</head>
<body>
	<div id="info">
		<div id="infolist">
			<form>
				<div class="input">
					 姓　　名：<input type="text" name="name" id="name" value="<?=$this->name?>" />
				</div>
				<div class="input">
					 工　　号：<input type="text" name="account" id="account" value="<?=$this->account ?>" readonly />
				</div>
				<div class="input">电　　话：<input type="text" name="phone" id="phone" /></div>
				<div class="input">邮　　箱：<input type="text" name="email" id="email" /></div>
			</form>
		</div>
		<div id="btn">
			<button type="submit" id="sub" title="提交信息">提交信息</button>
		</div>
	</div>	
</body>
</html>