<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/Teacher/teacher_information.css" type="text/css" rel='StyleSheet'>
</head>
<body>
	<table>
		<tr>
			<td class="title">姓名：</td><td><?=$this->name ?></td>
		</tr>
		<tr>
			<td class="title">工号：</td><td><?=$this->account ?></td>
		</tr>
		<tr>
			<td class="title">电话：</td><td><?=$this->phone ?></td>
		</tr>
		<tr>
			<td class="title">邮箱：</td><td><?=$this->email ?></td>
		</tr>
	</table>
</body>
</html>