<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="/css/login/find_password.css?2" rel="StyleSheet" type="text/css">
	<script src="/js/jquery-1.12.0.js" type="text/javascript"></script>
	<script src="/js/box/zDialog.js" type="text/javascript"></script>
	<script src="/js/login/find_password.js?2" type="text/javascript"></script>
</head>
<body>
	<div id="index">
		<a href="/Index/index" title="回到首页">首页</a>
	</div>
	<div id="findtable">
		<fieldset>
			<legend>找回密码</legend>
			<form>
				<div><input type="text" name="account" id="account"  placeholder="学号"><span id="account_note"></span></div>
				<div><input type="text" name="personId" id="personId"  placeholder="身份证号"><span id="personId_note"></span></div>
				<div><input type="password" name="newpassword" id="newpassword" placeholder="新密码"><span id="newpassword_note"></span></div>
				<div><input type="password" name="repassword" id="repassword" placeholder="确认密码"><span id="repassword_note"></span></div>	
			</form>
			<div id="btn">
				<button type="button" id="sub" title="修改密码">修改密码</button>
			</div>
		</fieldset>	
	</div>	
</body>
</html>